stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - export JAVA_HOME=/usr/java/jdk-14.0.1
    - ./mvnw clean package
  artifacts:
    paths:
      - target/saskcycle-Alpha.jar

test-job1:
  stage: test
  script:
    - export JAVA_HOME=/usr/java/jdk-14.0.1
    - ./mvnw test

